"""Init db schema

Revision ID: 51f150c4c1ae
Revises: 
Create Date: 2026-06-07 15:20:46.635684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f150c4c1ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pob_code', sa.Text(), nullable=False),
    sa.Column('pob_version', sa.String(length=32), nullable=True),
    sa.Column('class', sa.String(length=64), nullable=True),
    sa.Column('ascendancy', sa.String(length=64), nullable=True),
    sa.Column('main_skill', sa.String(length=128), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('build_data', sa.JSON(), nullable=False),
    sa.Column('homework', sa.JSON(), nullable=True),
    sa.Column('league', sa.String(length=64), nullable=True),
    sa.Column('game_version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mod_translations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mod_en', sa.Text(), nullable=False),
    sa.Column('mod_zh', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mod_en')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mod_translations')
    op.drop_table('builds')
    # ### end Alembic commands ###
