"""Shared table registry for GGPK import pipeline.

Single source of truth for all table names and their key fields.
Used by: export_en_tc.py, extract_sc.py, import_game_data.py,
         resolve_relations.py, resolve_string_fks.py, game_graph.py

Auto-generated: 416 tables (66 existing + 350 new)
"""

# All table names in the pipeline (without .dat suffix)
ALL_TABLES = [
    "AbyssObjects",
    "AchievementItems",
    "Achievements",
    "ActiveSkillType",
    "ActiveSkills",
    "Acts",
    "AdditionalLifeScaling",
    "AdvancedCraftingBenchCustomTags",
    "AdvancedCraftingBenchTabFilterTypes",
    "AfflictionBalancePerLevel",
    "AfflictionEndgameWaveMods",
    "AfflictionFixedMods",
    "AfflictionRandomModCategories",
    "AfflictionRewardMapMods",
    "AfflictionRewardTypeVisuals",
    "AfflictionSplitDemons",
    "AlternatePassiveAdditions",
    "AlternatePassiveSkills",
    "AncestralTrialUnits",
    "ArmourTypes",
    "Ascendancy",
    "AscendancyPassiveSkillOverrides",
    "AtlasExileBossArenas",
    "AtlasExileInfluence",
    "AtlasExiles",
    "AtlasFog",
    "AtlasInfluenceData",
    "AtlasInfluenceOutcomes",
    "AtlasInfluenceSets",
    "AtlasMemoryLine",
    "AtlasMods",
    "AtlasNode",
    "AtlasNodeDefinition",
    "AtlasPassiveSkillTreeGroupType",
    "AtlasPositions",
    "AtlasPrimordialAltarChoiceTypes",
    "AtlasPrimordialAltarChoices",
    "AtlasPrimordialBossInfluence",
    "AtlasPrimordialBossOptions",
    "AtlasPrimordialBosses",
    "AtlasRegions",
    "AtlasTowerInventoryLayout",
    "AtlasUpgradesInventoryLayout",
    "AttributeRequirements",
    "AzmeriFeatureRooms",
    "AzmeriWoodsDustType",
    "BaseItemTypes",
    "BestiaryCapturableMonsters",
    "BestiaryEncounters",
    "BestiaryFamilies",
    "BestiaryGenus",
    "BestiaryGroups",
    "BestiaryNets",
    "BestiaryRecipeCategories",
    "BestiaryRecipeComponent",
    "BestiaryRecipes",
    "BetrayalChoiceActions",
    "BetrayalChoices",
    "BetrayalDialogue",
    "BetrayalForts",
    "BetrayalJobs",
    "BetrayalRanks",
    "BetrayalRelationshipState",
    "BetrayalTargetLifeScalingPerLevel",
    "BetrayalTargets",
    "BetrayalTraitorRewards",
    "BetrayalUpgrades",
    "BlightBalancePerLevel",
    "BlightChestTypes",
    "BlightCraftingItems",
    "BlightCraftingRecipes",
    "BlightCraftingResults",
    "BlightCraftingUniques",
    "BlightEncounterTypes",
    "BlightRewardTypes",
    "BlightTopologies",
    "BlightTopologyNodes",
    "BlightTowerAuras",
    "BlightTowers",
    "BlightTowersPerLevel",
    "BlightedSporeAuras",
    "BossLifeScalingPerLevel",
    "BreachArtVariations",
    "BreachBossLifeScalingPerLevel",
    "BreachElement",
    "BuffDefinitions",
    "CharacterPanelStats",
    "CharacterStartStates",
    "ChestClusters",
    "Chests",
    "ClassPassiveSkillOverrides",
    "Colours",
    "ComponentCharges",
    "CraftableModTypes",
    "CraftingBenchOptions",
    "CraftingBenchSortCategories",
    "CraftingBenchSpecificOptionId",
    "CraftingBenchUnlockCategories",
    "CraftingItemClassCategories",
    "CurrencyConsumeEffects",
    "CurrencyExchange",
    "CurrencyExchangeCategories",
    "CurrencyItems",
    "CurrencyPerItemClassConditions",
    "CurrencyUseEffects",
    "CurrencyUseEffectsFromItem",
    "DamageCalculationTypes",
    "DefaultMonsterStats",
    "DelveAzuriteShop",
    "DelveBiomes",
    "DelveCatchupDepths",
    "DelveCraftingModifierDescriptions",
    "DelveCraftingModifiers",
    "DelveCraftingTags",
    "DelveDynamite",
    "DelveFeatures",
    "DelveFlares",
    "DelveLevelScaling",
    "DelveResourcePerLevel",
    "DelveRewardTierConstants",
    "DelveRobotVariations",
    "DelveRooms",
    "DelveUpgrades",
    "DisplayMinionMonsterType",
    "DivinationCardArt",
    "DivinationCardStashTabLayout",
    "EclipseMods",
    "EffectivenessCostConstants",
    "ElderBossArenas",
    "ElderGuardians",
    "ElderMapBossOverride",
    "EndgameCorruptionMods",
    "EndgameMapBiomes",
    "EndgameMapConstants",
    "EndgameMapContent",
    "EndgameMapContentSet",
    "EndgameMapDecorations",
    "EndgameMapObjectives",
    "EndgameMapPinIcons",
    "EndgameMapPins",
    "EndgameMapTablets",
    "EndgameMaps",
    "EndgameSplinterRecipes",
    "EssenceMods",
    "EssenceTargetItemCategories",
    "EssenceType",
    "Essences",
    "ExpeditionBalancePerLevel",
    "ExpeditionCurrency",
    "ExpeditionDeals",
    "ExpeditionDealsDialogue",
    "ExpeditionFactions",
    "ExpeditionMarkersCommon",
    "ExpeditionNPCs",
    "ExpeditionRelicMods",
    "ExpeditionRelics",
    "ExpeditionTerrainFeatures",
    "ExperienceLevels",
    "Flasks",
    "FlatPhysicalDamageValues",
    "FlavourText",
    "GameConstants",
    "GameStats",
    "GemTags",
    "GoldBaseTypePrices",
    "GoldModPrices",
    "GoldRespecPrices",
    "GoldVisualIdentities",
    "GrantedEffectLabels",
    "GrantedEffectQualityStats",
    "GrantedEffectStatSets",
    "GrantedEffectStatSetsPerLevel",
    "GrantedEffects",
    "GrantedEffectsPerLevel",
    "GrantedSkillSocketNumbers",
    "Harbingers",
    "HarvestCraftFilters",
    "HarvestCraftOptions",
    "HarvestCraftTiers",
    "HarvestInfrastructure",
    "HarvestSeedItems",
    "HarvestSeeds",
    "HeistAreaFormationLayout",
    "HeistAreas",
    "HeistBalancePerLevel",
    "HeistChestRewardTypes",
    "HeistChests",
    "HeistConstants",
    "HeistContracts",
    "HeistDoors",
    "HeistEquipment",
    "HeistGeneration",
    "HeistJobs",
    "HeistLockType",
    "HeistNPCDialogue",
    "HeistNPCStats",
    "HeistNPCs",
    "HeistObjectives",
    "HeistQuestContracts",
    "HeistStorageLayout",
    "HeistValueScaling",
    "HellscapeFactions",
    "HellscapeItemModificationTiers",
    "HellscapeLifeScalingPerLevel",
    "HellscapeMods",
    "HellscapePassiveTree",
    "HellscapePassives",
    "HideoutCraftingBenchDoodads",
    "HideoutDoodads",
    "HideoutNPCs",
    "HideoutSalvageBenchDoodads",
    "Hideouts",
    "IncubatorBaseRequiredKillsPerLevel",
    "Incubators",
    "Incursion2CorruptionCurrencies",
    "Incursion2Crafting",
    "Incursion2EncounterTilePerArea",
    "Incursion2Medallions",
    "Incursion2RoomPerLevel",
    "Incursion2Rooms",
    "Incursion2TempleLevelPerCharacterLevel",
    "IncursionArchitect",
    "IndexableSupportGems",
    "InfluenceExalts",
    "InfluenceModUpgrades",
    "InfluenceTags",
    "ItemClassCategories",
    "ItemClasses",
    "ItemConditions",
    "ItemDisenchantValues",
    "ItemExperiencePerLevel",
    "ItemExperienceTypes",
    "ItemFrameType",
    "ItemInherentSkills",
    "ItemSpirit",
    "ItemStances",
    "ItemToggleable",
    "ItemVisualIdentity",
    "ItemVisualReplacement",
    "LakeBossLifeScalingPerLevel",
    "LeagueFlag",
    "LeagueInfo",
    "LegionBalancePerLevel",
    "LegionChestCounts",
    "LegionChestTypes",
    "LegionFactions",
    "LegionMonsterCounts",
    "LegionMonsterVarieties",
    "LegionRanks",
    "LevelRelativePlayerScaling",
    "MapCompletionAchievements",
    "MapConnections",
    "MapCreationInformation",
    "MapDeviceRecipes",
    "MapDevices",
    "MapFragmentMods",
    "MapInhabitants",
    "MapPins",
    "MapSeries",
    "MapSeriesTiers",
    "MapStashSpecialTypeEntries",
    "MapStashUniqueMapInfo",
    "MapTierAchievements",
    "MapTiers",
    "Maps",
    "MavenDialog",
    "MavenFights",
    "MinionCommands",
    "MinionGemLevelScaling",
    "MinionStats",
    "MinionType",
    "ModFamily",
    "ModGrantedSkills",
    "ModSellPriceTypes",
    "ModType",
    "Mods",
    "MonsterArmours",
    "MonsterBonuses",
    "MonsterCategories",
    "MonsterConditionalEffectPacks",
    "MonsterConditions",
    "MonsterEncounterSkillGroups",
    "MonsterGroupEntries",
    "MonsterMapBossDifficulty",
    "MonsterMapDifficulty",
    "MonsterPackCounts",
    "MonsterPackEntries",
    "MonsterPacks",
    "MonsterResistances",
    "MonsterSegments",
    "MonsterTypes",
    "MonsterVarieties",
    "NPCConversations",
    "NPCDialogueStyles",
    "NPCMaster",
    "NPCPortraits",
    "NPCShop",
    "NPCShops",
    "NPCTalk",
    "NPCTalkCategory",
    "NPCTalkDialogue",
    "NPCType",
    "NPCs",
    "PantheonPanelLayout",
    "PassiveJewelArt",
    "PassiveJewelNodeModifyingStats",
    "PassiveJewelRadii",
    "PassiveJewelSlots",
    "PassiveJewelUniqueArt",
    "PassiveKeystoneList",
    "PassiveSkillFilterGroups",
    "PassiveSkillFilterOptions",
    "PassiveSkillMasteryEffects",
    "PassiveSkillMasteryGroups",
    "PassiveSkillOverrideTypes",
    "PassiveSkillOverrides",
    "PassiveSkillStatCategories",
    "PassiveSkillTrees",
    "PassiveSkills",
    "PassiveTreeExpansionJewelSizes",
    "PassiveTreeExpansionJewels",
    "PassiveTreeExpansionSkills",
    "PassiveTreeExpansionSpecialSkills",
    "PlayerBuffsFromMapStats",
    "PlayerMinionIntrinsicStats",
    "PrimordialBossLifeScalingPerLevel",
    "Quest",
    "QuestAchievements",
    "QuestFlags",
    "QuestRewardOffers",
    "QuestRewardType",
    "QuestRewards",
    "QuestStates",
    "QuestStaticRewards",
    "Rarity",
    "RecipeUnlockDisplay",
    "RecipeUnlockObjects",
    "RecombinableClasses",
    "ResistancePenaltyPerAreaLevel",
    "RitualBalancePerLevel",
    "RitualConstants",
    "RitualRuneTypes",
    "RitualSetKillAchievements",
    "RitualSpawnPatterns",
    "RogueExileModBonuses",
    "RogueExiles",
    "SafehouseBYOCrafting",
    "SalvageBoxes",
    "SanctumAirlocks",
    "SanctumBalancePerLevel",
    "SanctumDefenceIcons",
    "SanctumFloors",
    "SanctumFodderLifeScalingPerLevel",
    "SanctumLifeScalingPerLevel",
    "SanctumPersistentEffectCategories",
    "SanctumPersistentEffects",
    "SanctumRewardObjects",
    "SanctumRoomTypes",
    "SanctumRooms",
    "SanctumSelectionDisplayOverride",
    "Scarabs",
    "ScoutingReports",
    "SentinelPassiveStats",
    "SentinelPassiveTypes",
    "SentinelPassives",
    "ShaperGuardians",
    "ShieldTypes",
    "ShrineSounds",
    "ShrineVarieties",
    "Shrines",
    "SkillCraftingData",
    "SkillEvents",
    "SkillGemGoldPricePerLevel",
    "SkillGemGoldPricePerQuality",
    "SkillGemInfo",
    "SkillGemLevelUpEffects",
    "SkillGemSearchTerms",
    "SkillGemSupports",
    "SkillGems",
    "SoulCoreLimits",
    "SoulCoreStatCategories",
    "SoulCoreStats",
    "SoulCoreTypes",
    "SoulCores",
    "SpawnAdditionalChestsOrClusters",
    "StatDescriptions",
    "Stats",
    "StrongboxPacks",
    "SupportGemFamily",
    "SupportGems",
    "Tags",
    "TalismanMonsterMods",
    "TalismanPacks",
    "Talismans",
    "TieredCurrency",
    "UltimatumEncounterTypes",
    "UltimatumModifierTypes",
    "UltimatumModifiers",
    "UltimatumMonsterPackFamily",
    "UltimatumRooms",
    "UltimatumTrialLength",
    "UltimatumWagerTypes",
    "UncutGemTiers",
    "UncutGems",
    "UniqueChests",
    "UniqueJewelLimits",
    "UniqueMaps",
    "UtilityFlaskBuffs",
    "WarbandsGraph",
    "WarbandsPackMonsters",
    "WaystoneStashTabSubgroups",
    "WeaponClasses",
    "WeaponTypes",
    "WieldableClasses",
    "Words",
    "WorldAreas",
]

# Key field for each table.
# None = use positional index as fallback (no suitable unique column).
KEY_FIELDS: dict[str, str | None] = {
    "AbyssObjects": "Id",
    "AchievementItems": "Id",
    "Achievements": "Id",
    "ActiveSkillType": "Id",
    "ActiveSkills": "Id",
    "Acts": "Id",
    "AdditionalLifeScaling": "IntId",
    "AdvancedCraftingBenchCustomTags": "Id",
    "AdvancedCraftingBenchTabFilterTypes": "Id",
    "AfflictionBalancePerLevel": None,
    "AfflictionEndgameWaveMods": "ModsKey",
    "AfflictionFixedMods": "Rarity",
    "AfflictionRandomModCategories": "Id",
    "AfflictionRewardMapMods": "ModsKey",
    "AfflictionRewardTypeVisuals": "Id",
    "AfflictionSplitDemons": "MonsterVarietiesKey",
    "AlternatePassiveAdditions": "Id",
    "AlternatePassiveSkills": "Id",
    "AncestralTrialUnits": "Id",
    "ArmourTypes": "BaseItemType",
    "Ascendancy": "Id",
    "AscendancyPassiveSkillOverrides": "AscendancyToOverrideFor",
    "AtlasExileBossArenas": "Conqueror",
    "AtlasExileInfluence": "Conqueror",
    "AtlasExiles": "Id",
    "AtlasFog": None,
    "AtlasInfluenceData": "InfluencePack",
    "AtlasInfluenceOutcomes": "Id",
    "AtlasInfluenceSets": "Id",
    "AtlasMemoryLine": "League",
    "AtlasMods": "ModsKey",
    "AtlasNode": "Id",
    "AtlasNodeDefinition": "Id",
    "AtlasPassiveSkillTreeGroupType": "Id",
    "AtlasPositions": None,
    "AtlasPrimordialAltarChoiceTypes": "Id",
    "AtlasPrimordialAltarChoices": "Mod",
    "AtlasPrimordialBossInfluence": "Boss",
    "AtlasPrimordialBossOptions": "Name",
    "AtlasPrimordialBosses": "Id",
    "AtlasRegions": "Id",
    "AtlasTowerInventoryLayout": "Slot",
    "AtlasUpgradesInventoryLayout": "Id",
    "AttributeRequirements": "BaseItemType",
    "AzmeriFeatureRooms": None,
    "AzmeriWoodsDustType": "Id",
    "BaseItemTypes": "Id",
    "BestiaryCapturableMonsters": "MonsterVarietiesKey",
    "BestiaryEncounters": "Id",
    "BestiaryFamilies": "Id",
    "BestiaryGenus": "Id",
    "BestiaryGroups": "Id",
    "BestiaryNets": "BaseItemTypesKey",
    "BestiaryRecipeCategories": "Id",
    "BestiaryRecipeComponent": "Id",
    "BestiaryRecipes": "Id",
    "BetrayalChoiceActions": "Id",
    "BetrayalChoices": "Id",
    "BetrayalDialogue": "Id",
    "BetrayalForts": "Id",
    "BetrayalJobs": "Id",
    "BetrayalRanks": "Id",
    "BetrayalRelationshipState": "Id",
    "BetrayalTargetLifeScalingPerLevel": "Level",
    "BetrayalTargets": "Id",
    "BetrayalTraitorRewards": "BetrayalJobsKey",
    "BetrayalUpgrades": "Id",
    "BlightBalancePerLevel": "Level",
    "BlightChestTypes": "ChestsKey",
    "BlightCraftingItems": "BaseItemType",
    "BlightCraftingRecipes": "Id",
    "BlightCraftingResults": "Id",
    "BlightCraftingUniques": "WordsKey",
    "BlightEncounterTypes": "Id",
    "BlightRewardTypes": "Id",
    "BlightTopologies": "Id",
    "BlightTopologyNodes": "Id",
    "BlightTowerAuras": "Id",
    "BlightTowers": "Id",
    "BlightTowersPerLevel": "BlightTowersKey",
    "BlightedSporeAuras": "BuffDefinitionsKey",
    "BossLifeScalingPerLevel": "MonsterLevel",
    "BreachArtVariations": "Id",
    "BreachBossLifeScalingPerLevel": "MonsterLevel",
    "BreachElement": "Element",
    "BuffDefinitions": "Id",
    "CharacterPanelStats": "Id",
    "CharacterStartStates": "Id",
    "ChestClusters": "Id",
    "Chests": "Id",
    "ClassPassiveSkillOverrides": "CharacterToOverrideFor",
    "Colours": "Item",
    "ComponentCharges": "BaseItemTypesKey",
    "CraftableModTypes": "ModType",
    "CraftingBenchOptions": "Id",
    "CraftingBenchSortCategories": "Id",
    "CraftingBenchSpecificOptionId": None,
    "CraftingBenchUnlockCategories": "Id",
    "CraftingItemClassCategories": "Id",
    "CurrencyConsumeEffects": "BaeItemType",
    "CurrencyExchange": "Item",
    "CurrencyExchangeCategories": "Id",
    "CurrencyItems": "BaseItemType",
    "CurrencyPerItemClassConditions": "ItemClass",
    "CurrencyUseEffects": "Id",
    "CurrencyUseEffectsFromItem": "BaseItemType",
    "DamageCalculationTypes": "Id",
    "DefaultMonsterStats": "DisplayLevel",
    "DelveAzuriteShop": "BaseItemTypesKey",
    "DelveBiomes": "Id",
    "DelveCatchupDepths": "Level",
    "DelveCraftingModifierDescriptions": "Id",
    "DelveCraftingModifiers": "NegativeWeight_Values",
    "DelveCraftingTags": "TagsKey",
    "DelveDynamite": None,
    "DelveFeatures": "Id",
    "DelveFlares": "Id",
    "DelveLevelScaling": "Depth",
    "DelveResourcePerLevel": "AreaLevel",
    "DelveRewardTierConstants": None,
    "DelveRobotVariations": "Id",
    "DelveRooms": "DelveBiomesKey",
    "DelveUpgrades": "DelveUpgradeTypeKey",
    "DisplayMinionMonsterType": "MonsterVarietiesKey",
    "DivinationCardArt": "BaseItemTypesKey",
    "DivinationCardStashTabLayout": "StoredItem",
    "EclipseMods": "Key",
    "EffectivenessCostConstants": "Id",
    "ElderBossArenas": "WorldAreasKey",
    "ElderGuardians": "Id",
    "ElderMapBossOverride": "WorldAreasKey",
    "EndgameCorruptionMods": "CorruptionMod",
    "EndgameMapBiomes": "Id",
    "EndgameMapConstants": "Id",
    "EndgameMapContent": "Id",
    "EndgameMapContentSet": "Id",
    "EndgameMapDecorations": "Id",
    "EndgameMapObjectives": "Id",
    "EndgameMapPinIcons": "Id",
    "EndgameMapPins": "Id",
    "EndgameMapTablets": "BaseItemType",
    "EndgameMaps": "WorldArea",
    "EndgameSplinterRecipes": "BaseItemType",
    "EssenceMods": "Essence",
    "EssenceTargetItemCategories": "Id",
    "EssenceType": "Id",
    "Essences": "BaseItemType",
    "ExpeditionBalancePerLevel": "Level",
    "ExpeditionCurrency": "BaseItemType",
    "ExpeditionDeals": "Function",
    "ExpeditionDealsDialogue": None,
    "ExpeditionFactions": "Id",
    "ExpeditionMarkersCommon": "Id",
    "ExpeditionNPCs": "Id",
    "ExpeditionRelicMods": "Mod",
    "ExpeditionRelics": "Id",
    "ExpeditionTerrainFeatures": "Id",
    "ExperienceLevels": "Id",
    "Flasks": "BaseItemType",
    "FlatPhysicalDamageValues": "ScalingType",
    "FlavourText": "Id",
    "GameConstants": "Id",
    "GameStats": "Id",
    "GemTags": "Id",
    "GoldBaseTypePrices": "BaseItemType",
    "GoldModPrices": "Mod",
    "GoldRespecPrices": "Level",
    "GoldVisualIdentities": "Icon",
    "GrantedEffectLabels": "Id",
    "GrantedEffectQualityStats": "StatsValuesPermille",
    "GrantedEffectStatSets": "Id",
    "GrantedEffectStatSetsPerLevel": "StatSet",
    "GrantedEffects": "Id",
    "GrantedEffectsPerLevel": None,
    "GrantedSkillSocketNumbers": "Level",
    "Harbingers": "MonsterVarietiesKey",
    "HarvestCraftFilters": "Id",
    "HarvestCraftOptions": "Id",
    "HarvestCraftTiers": "Id",
    "HarvestInfrastructure": "Object",
    "HarvestSeedItems": "Id",
    "HarvestSeeds": "Id",
    "HeistAreaFormationLayout": "HeistAreasKey",
    "HeistAreas": "Id",
    "HeistBalancePerLevel": "Level",
    "HeistChestRewardTypes": "Id",
    "HeistChests": "ChestsKey",
    "HeistConstants": "Id",
    "HeistContracts": None,
    "HeistDoors": "Id",
    "HeistEquipment": "BaseItemTypesKey",
    "HeistGeneration": "Level",
    "HeistJobs": "Id",
    "HeistLockType": "Id",
    "HeistNPCDialogue": "DialogueEventKey",
    "HeistNPCStats": "StatsKey",
    "HeistNPCs": None,
    "HeistObjectives": "BaseItemType",
    "HeistQuestContracts": "HeistContractsKey",
    "HeistStorageLayout": "Id",
    "HeistValueScaling": "Id",
    "HellscapeFactions": "Id",
    "HellscapeItemModificationTiers": "Tier",
    "HellscapeLifeScalingPerLevel": "AreaLevel",
    "HellscapeMods": "Mod",
    "HellscapePassiveTree": "Id",
    "HellscapePassives": "Id",
    "HideoutCraftingBenchDoodads": "CraftingBench",
    "HideoutDoodads": None,
    "HideoutNPCs": None,
    "HideoutSalvageBenchDoodads": "HideoutDoodads",
    "Hideouts": None,
    "IncubatorBaseRequiredKillsPerLevel": "Level",
    "Incubators": "BaseItemType",
    "Incursion2CorruptionCurrencies": "BaseItemType",
    "Incursion2Crafting": "Id",
    "Incursion2EncounterTilePerArea": "Area",
    "Incursion2Medallions": "Id",
    "Incursion2RoomPerLevel": "Id",
    "Incursion2Rooms": "Id",
    "Incursion2TempleLevelPerCharacterLevel": "CharacterLevel",
    "IncursionArchitect": None,
    "IndexableSupportGems": "SupportGem",
    "InfluenceExalts": "Influence",
    "InfluenceModUpgrades": "InfluenceMod",
    "InfluenceTags": "ItemClass",
    "ItemClassCategories": "Id",
    "ItemClasses": "Id",
    "ItemConditions": "Id",
    "ItemDisenchantValues": "Rarity",
    "ItemExperiencePerLevel": None,
    "ItemExperienceTypes": "Id",
    "ItemFrameType": "Id",
    "ItemInherentSkills": "BaseItemType",
    "ItemSpirit": "BaseItemType",
    "ItemStances": "Id",
    "ItemToggleable": "BaseItemType",
    "ItemVisualIdentity": "Id",
    "ItemVisualReplacement": "Id",
    "LakeBossLifeScalingPerLevel": "Level",
    "LeagueFlag": "Id",
    "LeagueInfo": None,
    "LegionBalancePerLevel": "MinLevel",
    "LegionChestCounts": "LegionFactionsKey",
    "LegionChestTypes": "Key0",
    "LegionFactions": "Id",
    "LegionMonsterCounts": "LegionFactionsKey",
    "LegionMonsterVarieties": "MonsterVarietiesKey",
    "LegionRanks": None,
    "LevelRelativePlayerScaling": "PlayerLevel",
    "MapCompletionAchievements": None,
    "MapConnections": "MapPinsKey0",
    "MapCreationInformation": "MapsKey",
    "MapDeviceRecipes": "Id",
    "MapDevices": "Id",
    "MapFragmentMods": "BaseItemType",
    "MapInhabitants": "StatsKey",
    "MapPins": "Id",
    "MapSeries": "Id",
    "MapSeriesTiers": None,
    "MapStashSpecialTypeEntries": "Id",
    "MapStashUniqueMapInfo": "UniqueMap",
    "MapTierAchievements": "Id",
    "MapTiers": "Tier",
    "Maps": "BaseItemType",
    "MavenDialog": "Id",
    "MavenFights": "Id",
    "MinionCommands": "GrantedEffect",
    "MinionGemLevelScaling": "GemLevel",
    "MinionStats": "MinionStat",
    "MinionType": "Id",
    "ModFamily": "Id",
    "ModGrantedSkills": None,
    "ModSellPriceTypes": "Id",
    "ModType": None,
    "Mods": "Id",
    "MonsterArmours": "Id",
    "MonsterBonuses": "Id",
    "MonsterCategories": "Name",
    "MonsterConditionalEffectPacks": "Id",
    "MonsterConditions": "Id",
    "MonsterEncounterSkillGroups": "Id",
    "MonsterGroupEntries": "Id",
    "MonsterMapBossDifficulty": "MapLevel",
    "MonsterMapDifficulty": "MapLevel",
    "MonsterPackCounts": "Area",
    "MonsterPackEntries": "Id",
    "MonsterPacks": "Id",
    "MonsterResistances": "Id",
    "MonsterSegments": "Id",
    "MonsterTypes": "Id",
    "MonsterVarieties": "Id",
    "NPCConversations": "Id",
    "NPCDialogueStyles": "Id",
    "NPCMaster": "Id",
    "NPCPortraits": "Name",
    "NPCShop": "Id",
    "NPCShops": "Id",
    "NPCTalk": "NPCKey",
    "NPCTalkCategory": "Id",
    "NPCTalkDialogue": "Id",
    "NPCType": "Id",
    "NPCs": "Id",
    "PantheonPanelLayout": "Id",
    "PassiveJewelArt": "BaseItemTypesKey",
    "PassiveJewelNodeModifyingStats": "JwelStat",
    "PassiveJewelRadii": "ID",
    "PassiveJewelSlots": "Slot",
    "PassiveJewelUniqueArt": "Id",
    "PassiveKeystoneList": "Passive",
    "PassiveSkillFilterGroups": "Id",
    "PassiveSkillFilterOptions": "Id",
    "PassiveSkillMasteryEffects": "Id",
    "PassiveSkillMasteryGroups": "Id",
    "PassiveSkillOverrideTypes": "Id",
    "PassiveSkillOverrides": "Id",
    "PassiveSkillStatCategories": "Id",
    "PassiveSkillTrees": "Id",
    "PassiveSkills": "Id",
    "PassiveTreeExpansionJewelSizes": "Name",
    "PassiveTreeExpansionJewels": "BaseItemTypesKey",
    "PassiveTreeExpansionSkills": "PassiveSkillsKey",
    "PassiveTreeExpansionSpecialSkills": "PassiveSkillsKey",
    "PlayerBuffsFromMapStats": "Stat",
    "PlayerMinionIntrinsicStats": "Stat",
    "PrimordialBossLifeScalingPerLevel": "AreaLevel",
    "Quest": "Id",
    "QuestAchievements": "Id",
    "QuestFlags": "Id",
    "QuestRewardOffers": "Id",
    "QuestRewardType": "Id",
    "QuestRewards": "RewardOffer",
    "QuestStates": "Order",
    "QuestStaticRewards": "QuestFlag",
    "Rarity": "Id",
    "RecipeUnlockDisplay": "RecipeId",
    "RecipeUnlockObjects": "WorldAreasKey",
    "RecombinableClasses": "Id",
    "ResistancePenaltyPerAreaLevel": "AreaLevel",
    "RitualBalancePerLevel": "MinLevel",
    "RitualConstants": "Id",
    "RitualRuneTypes": "Id",
    "RitualSetKillAchievements": "Achievement",
    "RitualSpawnPatterns": "Id",
    "RogueExileModBonuses": "Mod",
    "RogueExiles": "MonsterVarietiesKey",
    "SafehouseBYOCrafting": "BetrayalJobsKey",
    "SalvageBoxes": "Id",
    "SanctumAirlocks": "Floor",
    "SanctumBalancePerLevel": "Level",
    "SanctumDefenceIcons": "Id",
    "SanctumFloors": "Id",
    "SanctumFodderLifeScalingPerLevel": "Level",
    "SanctumLifeScalingPerLevel": "Level",
    "SanctumPersistentEffectCategories": "Id",
    "SanctumPersistentEffects": "Id",
    "SanctumRewardObjects": "Id",
    "SanctumRoomTypes": "Id",
    "SanctumRooms": "Id",
    "SanctumSelectionDisplayOverride": "Id",
    "Scarabs": "BaseItemType",
    "ScoutingReports": "Id",
    "SentinelPassiveStats": "Key0",
    "SentinelPassiveTypes": "Id",
    "SentinelPassives": "Id",
    "ShaperGuardians": "Id",
    "ShieldTypes": "BaseItemType",
    "ShrineSounds": "Id",
    "ShrineVarieties": "Tag",
    "Shrines": "Id",
    "SkillCraftingData": "Id",
    "SkillEvents": "Id",
    "SkillGemGoldPricePerLevel": "Level",
    "SkillGemGoldPricePerQuality": "Quality",
    "SkillGemInfo": "Id",
    "SkillGemLevelUpEffects": "Id",
    "SkillGemSearchTerms": "Id",
    "SkillGemSupports": "SkillGem",
    "SkillGems": "BaseItemType",
    "SoulCoreLimits": "Id",
    "SoulCoreStatCategories": "Id",
    "SoulCoreStats": "SoulCore",
    "SoulCoreTypes": "Id",
    "SoulCores": "BaseItemType",
    "SpawnAdditionalChestsOrClusters": "StatsKey",
    "StatDescriptions": "Id",
    "Stats": "Id",
    "StrongboxPacks": "Id",
    "SupportGemFamily": "Id",
    "SupportGems": "SkillGem",
    "Tags": "Id",
    "TalismanMonsterMods": "ModTypeKey",
    "TalismanPacks": "Id",
    "Talismans": "BaseItemTypesKey",
    "TieredCurrency": "BaseItemType",
    "UltimatumEncounterTypes": "Id",
    "UltimatumModifierTypes": "Id",
    "UltimatumModifiers": "Id",
    "UltimatumMonsterPackFamily": "Id",
    "UltimatumRooms": "Id",
    "UltimatumTrialLength": "MinAreaLevel",
    "UltimatumWagerTypes": "Id",
    "UncutGemTiers": "BaseItemType",
    "UncutGems": "BaseItemType",
    "UniqueChests": "Id",
    "UniqueJewelLimits": "JewelName",
    "UniqueMaps": None,
    "UtilityFlaskBuffs": "BuffDefinition",
    "WarbandsGraph": "WorldAreasKey",
    "WarbandsPackMonsters": "Id",
    "WaystoneStashTabSubgroups": "Tier",
    "WeaponClasses": "Name",
    "WeaponTypes": "BaseItemType",
    "WieldableClasses": "ItemClass",
    "Words": "Id",
    "WorldAreas": "Id",
}


def get_key_field(table_name: str) -> str | None:
    """Get the key field for a table, with Id fallback for unknown tables."""
    return KEY_FIELDS.get(table_name, "Id")